### ISSUE TITLE
Issue running this on a real device (CAMetalLayer nextDrawable)

### ISSUE THREAD

**Issue by csoutham** [robjperez/opentok-swiftui-sample#2]
Once upgraded to v2.17.0 and the correct permissions are assigned for camera and microphone this will build on a real device.
However once connected to OpenTok it throws constant errors, with no camera output:
opentok-swiftui-sample[21059:7974299] [CAMetalLayer nextDrawable] returning nil because allocation failed.

Appreciate you may have abandoned this @robjperez but it's the only (almost) working example out there!

**Comment by robjperez** [comment]
Thanks for reporting @csoutham 
I’ll take it a look :)

**Comment by robjperez** [comment]
@csoutham it should be fixed in last commit in master branch

Please reopen if it is still not working :)
